Repository project-swap/swap, pull requests merged in 2023-02, with the labels that each got.

#33 이미지 업로드 & 프리뷰 및 닉네임 검증 부분 수정
  src/atoms/atoms.ts
  src/components/ProfileModal.tsx
  src/components/chatting/UserChatInput.tsx
  src/components/chatting/UserChatMessage.tsx
  src/components/chatting/UserChatMessageArea.tsx
  src/components/chatting/UserChatNameBox.tsx
  src/components/common/Footer.tsx
  src/components/common/NavBar.jsx
  src/components/main/Banner.tsx
  src/components/main/ExchangeAndShareList.tsx
  src/components/main/HashtagAndBannerContainer.tsx
  src/components/main/PopularHashtag.tsx
  src/components/main/PopularPost.tsx
  src/components/main/SectionContainer.tsx
  src/components/main/SectionTitle.tsx
  src/components/main/ThemeBtn.tsx
  src/components/registerProduct/RegisterProduct.jsx
  src/components/registerProduct/RegisterProductImageUploadGroup.jsx
  src/components/registerProduct/RegisterProductInputGroup.jsx
  src/components/registerProduct/RegisterProductPostBtn.jsx
  src/components/registerProduct/RegisterProductTradeTypeGroup.jsx
  src/components/swap/SalesProductCard.jsx
  src/components/swap/SalesProductCardGroup.jsx
  src/components/swap/SalesProductList.jsx
  src/components/swap/SalesProductListTap.jsx
  src/pages/Main.tsx
  src/pages/Register.jsx
  src/pages/Swap.jsx
  src/pages/UserChatting.tsx
  src/pages/mypage/Profile.tsx
Labels: style, feature, [FE]정하승

#37 children 타입 수정, 사이드바 스타일 수정
  src/components/BookMarkContainerChildren.tsx
  src/components/ContainerChildren.tsx
  src/components/ContentChildren.tsx
  src/components/ExchangeContainerChildren.tsx
  src/components/ProfileModal.tsx
  src/components/ReportHistoryChildren.tsx
  src/components/SideBar.tsx
  src/components/common/MainContainer.tsx
  src/pages/Router.js
  src/pages/my_page/BookMarkPage.tsx
  src/pages/my_page/ExchangeHistory.tsx
  src/pages/my_page/LocationSetting.tsx
  src/pages/my_page/Mypage.tsx
  src/pages/my_page/Profile.tsx
  src/pages/my_page/ReportHistory.tsx
  src/utils/utils.js
  src/utils/utils.ts
Labels: style, [FE]정하승, chore

#40 CRUD 중 create와 read (병합 수동해결) 및 타입스크립트 마이그레이션
  .vscode/launch.json
  src/apis/api.ts
  src/atoms/atoms.ts
  src/components/Follow/FollowComponent.jsx
  src/components/Follow/FollowList.jsx
  src/components/Follow/FollowMenuBar.jsx
  src/components/Follow/User.jsx
  src/components/Main/Banner.tsx
  src/components/Main/ExchangeAndShareList.tsx
  src/components/Main/HashtagAndBannerContainer.tsx
  src/components/Main/PopularHashtag.tsx
  src/components/Main/PopularPost.tsx
  src/components/Main/SectionContainer.tsx
  src/components/Main/SectionTitle.tsx
  src/components/Main/ThemeBtn.tsx
  src/components/common/NavBar.tsx
  src/components/common/PublicStyle.tsx
  src/components/common/product_card/ArticlePreview.tsx
  src/components/common/product_card/PostingTime.tsx
  src/components/common/product_card/ProductCardFrame.tsx
  src/components/common/product_card/ProductImg.tsx
  src/components/common/product_card/ProfileImg.tsx
  src/components/common/product_card/SalesTitle.tsx
  src/components/common/product_card/SellerName.tsx
  src/components/product_detail/BuyerMenuBar.tsx
  src/components/product_detail/Content.tsx
  src/components/product_detail/PostInfo.tsx
  src/components/product_detail/ProductDetail.tsx
  src/components/product_detail/ProductDetailComponent.tsx
  src/components/product_detail/ProductImgList.tsx
  src/components/product_detail/SellerInfo.tsx
  src/components/product_detail/Title.tsx
  src/components/registerProduct/RegisterProduct.jsx
  src/components/registerProduct/RegisterProductImageUploadGroup.jsx
  src/components/registerProduct/RegisterProductInputGroup.jsx
  src/components/registerProduct/RegisterProductTradeTypeGroup.jsx
  src/components/register_product/HashtagInput.tsx
  src/components/register_product/RegisterProduct.tsx
  src/components/register_product/RegisterProductImageUploadGroupFirebase.tsx
  src/components/register_product/RegisterProductInputContent.tsx
  src/components/register_product/RegisterProductInputGroup.tsx
  src/components/register_product/RegisterProductPostBtn.tsx
  src/components/register_product/RegisterProductTradeTypeGroup.tsx
  src/components/sales_product/SalesProductCard.tsx
  src/components/sales_product/SalesProductCardGroup.tsx
  src/components/sales_product/SalesProductList.tsx
  src/components/sales_product/SalesProductListTap.tsx
  src/components/swap/SalesProductList.jsx
  src/components/swap/SalesProductListTap.jsx
  src/firebase.ts
  src/pages/DetailPage.tsx
  src/pages/Follow.tsx
  src/pages/Register.tsx
  src/pages/Router.js
  src/pages/SalesProduct.tsx
Labels: feature, [FE]박소예

#43 closeEvent 추가
  src/components/ProfileModal.tsx
Labels: [FE]정하승

#45 프로필에 NavBar 추가, 프로필페이지로 가는 링크 추가
  src/components/ProfileModal.tsx
  src/components/common/Footer.tsx
  src/components/common/NavBar.tsx
  src/pages/Follow.tsx
  src/pages/Main.tsx
  src/pages/my_page/Profile.tsx
Labels: style, [FE]정하승
